import './slideshow/slideshow.constructor.js'
import './slideshow/slideshow.base.js'
import './slideshow/slideshow.animation.js'
import './slideshow/slideshow.calculation.js'
import './slideshow/slideshow.modules.js'
